In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
arr = np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
arr.transpose([2, 0, 1]) # shape = (4, 2, 3)

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("array shape => ", arr3d.shape)
print(arr3d)

arr3d.swapaxes(1, 2) # change axis1 and axis2

array shape =>  (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [39]:
np.random.seed(123)
print(np.random.randn(10))
np.random.seed(123) 
print(np.fabs(np.random.randn(10)))

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
[1.0856306  0.99734545 0.2829785  1.50629471 0.57860025 1.65143654
 2.42667924 0.42891263 1.26593626 0.8667404 ]


In [54]:
arr = np.array([[0, 1, 2], [3, 4, 4], [6, 7, 8]])
print(arr)
print("-"*25 + 'cumsum method'+ "-"*25)
print(arr.cumsum(axis = 0))
print("-"*25 + 'cumprod method'+ "-"*25)
print(arr.cumprod(axis = 0))

[[0 1 2]
 [3 4 4]
 [6 7 8]]
-------------------------cumsum method-------------------------
[[ 0  1  2]
 [ 3  5  6]
 [ 9 12 14]]
-------------------------cumprod method-------------------------
[[ 0  1  2]
 [ 0  4  8]
 [ 0 28 64]]


In [69]:
np.random.seed(123)
arr = np.random.randn(5, 3)
arr.sort(axis = 0)

array([[-2.42667924, -0.67888615, -0.44398196],
       [-1.50629471, -0.638902  , -0.09470897],
       [-1.0856306 , -0.57860025,  0.2829785 ],
       [-0.8667404 , -0.42891263,  1.26593626],
       [ 1.49138963,  0.99734545,  1.65143654]])

### np.where

In [73]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [76]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [81]:
arr = np.random.randn(4, 4)
np.where(arr > 2, 2, -2)

array([[-2, -2, -2, -2],
       [-2, -2, -2, -2],
       [-2, -2, -2, -2],
       [-2, -2, -2, -2]])

In [88]:
bools = np.array([False, False, True, False])
print("any method => ", bools.any()) # whether one or more values in an array is True
print("all method => ", bools.all())

any method =>  True
all method =>  False


In [91]:
bools = np.array([False, False])
bools.any()

False

In [93]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(ar1 = values, ar2 = [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

### Set operation

In [102]:
value1 = np.array([2, 3, 6, 4, 3])
value2 = np.array([2, 5, 7, 4, 3])

print("-"*5 + "Intersection" + '-'*5)
print(np.intersect1d(ar1 = value1, ar2 = value2))

print("-"*5 + "Union" + '-'*5)
print(np.union1d(ar1 = value1, ar2 = value2))

# set difference, elements in x that aren't in y.
print("-"*5 + "difference" + '-'*5)
print(np.setdiff1d(ar1 = value1, ar2 = value2))

print("-"*5 + "symmetric difference" + '-'*5)
print(np.setxor1d(ar1 = value1, ar2 = value2))

-----Intersection-----
[2 3 4]
-----Union-----
[2 3 4 5 6 7]
-----difference-----
[6]
-----symmetric difference-----
[5 6 7]


### Random Number Generation

In [106]:
samples = np.random.normal(loc = 0, scale = 1, size = (4, 4))
samples

array([[ 1.03111446, -1.08456791, -1.36347154,  0.37940061],
       [-0.37917643,  0.64205469, -1.97788793,  0.71226464],
       [ 2.59830393, -0.02462598,  0.03414213,  0.17954948],
       [-1.86197571,  0.42614664, -1.60540974, -0.4276796 ]])